import Vue from "vue";
import Vuex from "vuex";

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    deck: {
      id: "001",
      name: "Black Vampires",
      cards: [
        { name: "Swamp", imageUrl: "", count: 8 },
        { name: "Arguel's Blood Fast", imageUrl: "", count: 1 },
        { name: "Bloodghast", imageUrl: "", count: 3 },
        { name: "Cordial Vampire", imageUrl: "", count: 3 },
        { name: "Knight of the Ebon Legion", imageUrl: "", count: 3 },
        { name: "Sorin, Imperious Bloodlord", imageUrl: "", count: 4 },
        { name: "Bloodletter of Aclazotz", imageUrl: "", count: 2 },
        { name: "Evelyn, the Covetous", imageUrl: "", count: 1 },
        { name: "Agadeem's Awakening", imageUrl: "", count: 4 },
        { name: "Castle Locthwain", imageUrl: "", count: 1 },
        { name: "Nykthos, Shrine to Nyx", imageUrl: "", count: 1 },
        { name: "Voldaren Estate", imageUrl: "", count: 4 },
        { name: "Ifnir Deadlands", imageUrl: "", count: 4 },
        { name: "Dusk's Landing", imageUrl: "", count: 2 },
        { name: "Thoughtseize", imageUrl: "", count: 2 },
        { name: "Font of Agonies", imageUrl: "", count: 3 },
        { name: "Phyrexian Reclamation", imageUrl: "", count: 1 },
        { name: "Vito, Thorn of the Dusk Rose", imageUrl: "", count: 1 },
        { name: "Bloodchief's Thirst", imageUrl: "", count: 1 },
        { name: "Drana, Liberator of Malakir", imageUrl: "", count: 1 },
        { name: "Indulgent Aristocrat", imageUrl: "", count: 3 },
        { name: "Bitter Triumph", imageUrl: "", count: 2 },
        { name: "Demolition Field", imageUrl: "", count: 2 },
        { name: "Vraan, Executioner Thane", imageUrl: "", count: 1 },
        { name: "Feed the Swarm", imageUrl: "", count: 2 },
      ],
      sideBoard: [
        { name: "Kinzu of the Bleak Coven", imageUrl: "", count: 1 },
        { name: "Voldaren Bloodcaster", imageUrl: "", count: 1 },
        { name: "A-Blood Artist", imageUrl: "", count: 1 },
        { name: "Vona's Hunger", imageUrl: "", count: 1 },
        { name: "Preacher of the Schism", imageUrl: "", count: 1 },
        { name: "Fatal Push", imageUrl: "", count: 1 },
        { name: "Sanguine Brushstroke", imageUrl: "", count: 1 },
        { name: "Witch's Vengeance", imageUrl: "", count: 1 },
        { name: "Yahenni, Undying Partisan", imageUrl: "", count: 1 },
        { name: "Henrika Domnathi", imageUrl: "", count: 1 },
        { name: "Nighthawk Scavenger", imageUrl: "", count: 1 },
        { name: "Vein Ripper", imageUrl: "", count: 1 },
        { name: "Queen's Bay Paladin", imageUrl: "", count: 1 },
        { name: "Roaming Throne", imageUrl: "", count: 1 },
        { name: "Callous Bloodmage", imageUrl: "", count: 1 },
      ],
    },
  },
  getters: {},
  mutations: {},
  actions: {},
  modules: {},
});
